### ISSUE TITLE
ログインWidgetの修正

### ISSUE THREAD

**Issue by yayamochi** [teamb-prince/pinterest_prince_flutter#99]
- [x] passwordとconfirmpasswordの確認のアラート
- [x] バリデーション(emailやpasswordの制限/ユーザーidがかぶっていないか?)
- [x] passwordを見えなくする処理
- [x] 間違っているときのアラートの表示周り

**Comment by yayamochi** [comment]
@TatsuhiroAbe 
>passwordを見えなくする処理

これ、Blocでやるほどのことでもないような気がするんだけど、Changenotifierとかで実装して変えたほうがいいかな？
それともこれもBlocに合わせた方が統一感あっていいかな。

**Comment by TatsuhiroAbe** [comment]
TextFormFiled使ってるから、_obscureText設定すればいいと思ってた。
ただ、やり方はまかせます！

**Comment by yayamochi** [comment]
その_obscureTextをtrue/falseにするときって、State変更通知しなくてもうごくんやっけ

**Comment by TatsuhiroAbe** [comment]
その程度ならsetState()でもいいかなって認識だった。どうかな？

**Comment by yayamochi** [comment]
考えてみる
